basePath: /api
definitions:
  dto.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  dto.PatientResponse:
    properties:
      created_at:
        type: string
      date_of_birth:
        type: string
      email:
        type: string
      first_name_en:
        type: string
      first_name_th:
        type: string
      gender:
        type: string
      hospital_id:
        type: string
      last_name_en:
        type: string
      last_name_th:
        type: string
      middle_name_en:
        type: string
      middle_name_th:
        type: string
      national_id:
        type: string
      passport_id:
        type: string
      patient_hn:
        type: string
      patient_id:
        type: string
      phone_number:
        type: string
      updated_at:
        type: string
    type: object
  dto.PatientSearchCriteria:
    properties:
      date_of_birth:
        type: string
      email:
        type: string
      first_name:
        type: string
      hospital_id:
        type: string
      last_name:
        type: string
      middle_name:
        type: string
      national_id:
        type: string
      passport_id:
        type: string
      phone_number:
        type: string
    type: object
  dto.StaffCreateRequest:
    properties:
      hospital_id:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - hospital_id
    - password
    - username
    type: object
  dto.StaffLoginRequest:
    properties:
      hospital_id:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - hospital_id
    - password
    - username
    type: object
  dto.StaffLoginResponse:
    properties:
      token:
        type: string
    type: object
  dto.StaffResponse:
    properties:
      created_at:
        type: string
      hospital_id:
        type: string
      staff_id:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: jakkrid.wi@gmail.com
    name: developer
  description: This is a exam for hospital api.
  title: Hospital API
  version: "1.0"
paths:
  /patients/search:
    post:
      consumes:
      - application/json
      parameters:
      - description: Search Criteria
        in: body
        name: search
        required: true
        schema:
          $ref: '#/definitions/dto.PatientSearchCriteria'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.PatientResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      tags:
      - patients
  /staff:
    post:
      consumes:
      - application/json
      description: Create a new staff
      parameters:
      - description: Staff info
        in: body
        name: staff
        required: true
        schema:
          $ref: '#/definitions/dto.StaffCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.StaffResponse'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Create staff
      tags:
      - staff
  /staff/login:
    post:
      consumes:
      - application/json
      description: Login an existing staff
      parameters:
      - description: Staff login info
        in: body
        name: staff
        required: true
        schema:
          $ref: '#/definitions/dto.StaffLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.StaffLoginResponse'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "401":
          description: unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Login staff
      tags:
      - staff
securityDefinitions:
  BearerAuth:
    description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization:
      Bearer {token}"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
